# Generated by Django 5.1.6 on 2025-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
