# Generated by Django 5.1.1 on 2025-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_testfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfiles',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
