# Generated by Django 5.1.1 on 2025-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_testfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfiles',
            name='endTime',
            field=models.DateTimeField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfiles',
            name='startTime',
            field=models.DateTimeField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
