# Generated by Django 5.1.1 on 2025-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_testfiles_endtime_testfiles_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfiles',
            name='courseCode',
            field=models.CharField(default='no', max_length=4),
            preserve_default=False,
        ),
    ]
