# Generated by Django 5.1.1 on 2025-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_testfiles_coursecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='testfiles',
            name='Afiles',
            field=models.FileField(default='no', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfiles',
            name='Qfiles',
            field=models.FileField(default='no', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
