# Generated by Django 5.1.1 on 2025-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_testfiles_file_testfiles_afiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfiles',
            name='courseCode',
            field=models.CharField(max_length=6),
        ),
    ]
