# Generated by Django 5.1.1 on 2025-03-23 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='test',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.testfiles'),
        ),
    ]
