# Generated by Django 5.1.1 on 2025-03-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_scores_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=10)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
            ],
            options={
                'unique_together': {('classid', 'courseID')},
            },
        ),
    ]
