# Generated by Django 5.1.1 on 2025-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_courses_classcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testfiles')),
            ],
        ),
    ]
