# Generated by Django 5.1.1 on 2025-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_studenttestrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
