# Generated by Django 5.1.1 on 2025-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_studenttestrecord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttestrecord',
            old_name='is_passed',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='studenttestrecord',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='studenttestrecord',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='studenttestrecord',
            name='correct_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studenttestrecord',
            name='incorrect_answers',
            field=models.JSONField(default=list),
        ),
    ]
