# Generated by Django 5.1.1 on 2025-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_is_passed_studenttestrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestrecord',
            name='user_answers',
            field=models.JSONField(default=list),
        ),
    ]
