# Generated by Django 5.1.1 on 2025-03-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_teacherlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='course',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='login',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='login',
            name='stuName',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
