# Generated by Django 5.1.1 on 2025-03-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_login_course_login_mail_login_stuname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='stuName',
        ),
    ]
